version: "3.4"

services:
  python-module:
    # image: python-module
    # build: ./python-module/.
    image: igcrawler:0.0.2
    shm_size: 2gb
    env_file:
      - ./env/python-module.env
    volumes:
      - ./src:/app/src
